/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controler.Control;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author samue
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LNome = new javax.swing.JLabel();
        LCPF = new javax.swing.JLabel();
        LLogin = new javax.swing.JLabel();
        LSenha = new javax.swing.JLabel();
        FTNome = new javax.swing.JFormattedTextField();
        FTCPF = new javax.swing.JFormattedTextField();
        FTLogin = new javax.swing.JFormattedTextField();
        LTitulo = new javax.swing.JLabel();
        BCadastro = new javax.swing.JButton();
        PFSenha = new javax.swing.JPasswordField();
        LTelaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        LNome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LNome.setForeground(new java.awt.Color(102, 255, 102));
        LNome.setText("NOME:");
        getContentPane().add(LNome);
        LNome.setBounds(259, 142, 101, 29);

        LCPF.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LCPF.setForeground(new java.awt.Color(102, 255, 102));
        LCPF.setText("CPF:");
        getContentPane().add(LCPF);
        LCPF.setBounds(263, 211, 59, 25);

        LLogin.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LLogin.setForeground(new java.awt.Color(102, 255, 102));
        LLogin.setText("LOGIN:");
        getContentPane().add(LLogin);
        LLogin.setBounds(259, 270, 56, 26);

        LSenha.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LSenha.setForeground(new java.awt.Color(102, 255, 102));
        LSenha.setText("SENHA:");
        getContentPane().add(LSenha);
        LSenha.setBounds(262, 336, 68, 30);
        getContentPane().add(FTNome);
        FTNome.setBounds(259, 183, 210, 22);
        getContentPane().add(FTCPF);
        FTCPF.setBounds(259, 242, 206, 22);

        FTLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTLoginActionPerformed(evt);
            }
        });
        getContentPane().add(FTLogin);
        FTLogin.setBounds(259, 308, 206, 22);

        LTitulo.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        LTitulo.setForeground(new java.awt.Color(102, 255, 102));
        LTitulo.setText("TELA CADASTRO");
        getContentPane().add(LTitulo);
        LTitulo.setBounds(208, 51, 359, 79);

        BCadastro.setText("CADASTRAR");
        BCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(BCadastro);
        BCadastro.setBounds(310, 420, 120, 30);
        getContentPane().add(PFSenha);
        PFSenha.setBounds(260, 370, 210, 22);

        LTelaFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\samue\\Documents\\NetBeansProjects\\Bibliotecas\\src\\main\\java\\Imagens\\linguagem-de-programação.jpg")); // NOI18N
        getContentPane().add(LTelaFundo);
        LTelaFundo.setBounds(-100, -20, 920, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FTLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTLoginActionPerformed

    private void BCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastroActionPerformed
        try {
            Control crt = new Control();
            
            crt.Cadastrar(Integer.parseInt(FTCPF.getText()), FTNome.getText(), FTLogin.getText(), PFSenha.getText());
            
            TelaInicial Ti = new TelaInicial();
            Ti.setVisible(true);
            
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCadastro;
    private javax.swing.JFormattedTextField FTCPF;
    private javax.swing.JFormattedTextField FTLogin;
    private javax.swing.JFormattedTextField FTNome;
    private javax.swing.JLabel LCPF;
    private javax.swing.JLabel LLogin;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LSenha;
    private javax.swing.JLabel LTelaFundo;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JPasswordField PFSenha;
    // End of variables declaration//GEN-END:variables
}
