/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controler.Control;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author samue
 */
public class TelaInseriLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaInseriLivro
     */
    public TelaInseriLivro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LAutor1 = new javax.swing.JLabel();
        LAutor2 = new javax.swing.JLabel();
        LTitulo = new javax.swing.JLabel();
        LEdicao = new javax.swing.JLabel();
        LCidade = new javax.swing.JLabel();
        LEditora = new javax.swing.JLabel();
        LAno = new javax.swing.JLabel();
        LNumPag = new javax.swing.JLabel();
        LTam = new javax.swing.JLabel();
        LIsbn = new javax.swing.JLabel();
        LAssunto = new javax.swing.JLabel();
        LPalChave1 = new javax.swing.JLabel();
        LPalChave2 = new javax.swing.JLabel();
        LTituloFIm = new javax.swing.JLabel();
        LCdu = new javax.swing.JLabel();
        FTAutor1 = new javax.swing.JFormattedTextField();
        FTNumPag = new javax.swing.JFormattedTextField();
        FTTam = new javax.swing.JFormattedTextField();
        FTAutor2 = new javax.swing.JFormattedTextField();
        FTIsbn = new javax.swing.JFormattedTextField();
        FTTitulo = new javax.swing.JFormattedTextField();
        FTAssunto = new javax.swing.JFormattedTextField();
        FTNumEd = new javax.swing.JFormattedTextField();
        FTPalChave1 = new javax.swing.JFormattedTextField();
        FTCidade = new javax.swing.JFormattedTextField();
        FTEditora = new javax.swing.JFormattedTextField();
        FTChave2 = new javax.swing.JFormattedTextField();
        FTAno = new javax.swing.JFormattedTextField();
        FTTituloFim = new javax.swing.JFormattedTextField();
        FTCdu = new javax.swing.JFormattedTextField();
        BInser = new javax.swing.JButton();
        BCancel = new javax.swing.JButton();
        CBAcervo = new javax.swing.JComboBox<>();
        BTelaIni = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\samue\\Documents\\NetBeansProjects\\Bibliotecas\\src\\main\\java\\Imagens\\question-mark-5483259_960_720.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(867, 590));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSERI LIVROS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 0, 311, 65);

        LAutor1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LAutor1.setForeground(new java.awt.Color(255, 255, 255));
        LAutor1.setText("AUTOR 1:");
        getContentPane().add(LAutor1);
        LAutor1.setBounds(130, 100, 100, 17);

        LAutor2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LAutor2.setForeground(new java.awt.Color(255, 255, 255));
        LAutor2.setText("AUTOR 2:");
        getContentPane().add(LAutor2);
        LAutor2.setBounds(330, 100, 90, 17);

        LTitulo.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LTitulo.setText("TITULO DA OBRAS:");
        getContentPane().add(LTitulo);
        LTitulo.setBounds(530, 100, 170, 17);

        LEdicao.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LEdicao.setForeground(new java.awt.Color(255, 255, 255));
        LEdicao.setText("NUMERO DE EDIÇÃO");
        getContentPane().add(LEdicao);
        LEdicao.setBounds(130, 190, 180, 17);

        LCidade.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LCidade.setForeground(new java.awt.Color(255, 255, 255));
        LCidade.setText("CIDADE:");
        getContentPane().add(LCidade);
        LCidade.setBounds(330, 190, 120, 30);

        LEditora.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LEditora.setForeground(new java.awt.Color(255, 255, 255));
        LEditora.setText("EDITORA");
        getContentPane().add(LEditora);
        LEditora.setBounds(530, 180, 90, 50);

        LAno.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LAno.setForeground(new java.awt.Color(255, 255, 255));
        LAno.setText("ANO:");
        getContentPane().add(LAno);
        LAno.setBounds(130, 260, 80, 50);

        LNumPag.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LNumPag.setForeground(new java.awt.Color(255, 255, 255));
        LNumPag.setText("NUMERO DE PAGINAS:");
        getContentPane().add(LNumPag);
        LNumPag.setBounds(530, 280, 200, 17);

        LTam.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LTam.setForeground(new java.awt.Color(255, 255, 255));
        LTam.setText("TAMANHO EM CM:");
        getContentPane().add(LTam);
        LTam.setBounds(130, 360, 160, 17);

        LIsbn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LIsbn.setForeground(new java.awt.Color(255, 255, 255));
        LIsbn.setText("ISBN:");
        getContentPane().add(LIsbn);
        LIsbn.setBounds(330, 360, 110, 17);

        LAssunto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LAssunto.setForeground(new java.awt.Color(255, 255, 255));
        LAssunto.setText("ASSUNTO:");
        getContentPane().add(LAssunto);
        LAssunto.setBounds(530, 360, 90, 17);

        LPalChave1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LPalChave1.setForeground(new java.awt.Color(255, 255, 255));
        LPalChave1.setText("PALAVRA CHAVE:");
        getContentPane().add(LPalChave1);
        LPalChave1.setBounds(130, 420, 170, 40);

        LPalChave2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LPalChave2.setForeground(new java.awt.Color(255, 255, 255));
        LPalChave2.setText("PALAVRA CHAVE 2:");
        getContentPane().add(LPalChave2);
        LPalChave2.setBounds(330, 420, 160, 50);

        LTituloFIm.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LTituloFIm.setForeground(new java.awt.Color(255, 255, 255));
        LTituloFIm.setText("TITULO:");
        getContentPane().add(LTituloFIm);
        LTituloFIm.setBounds(330, 260, 120, 50);

        LCdu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LCdu.setForeground(new java.awt.Color(255, 255, 255));
        LCdu.setText("CDU:");
        getContentPane().add(LCdu);
        LCdu.setBounds(540, 430, 40, 30);
        getContentPane().add(FTAutor1);
        FTAutor1.setBounds(130, 130, 180, 30);
        getContentPane().add(FTNumPag);
        FTNumPag.setBounds(530, 310, 180, 30);
        getContentPane().add(FTTam);
        FTTam.setBounds(130, 390, 180, 30);
        getContentPane().add(FTAutor2);
        FTAutor2.setBounds(330, 130, 180, 30);
        getContentPane().add(FTIsbn);
        FTIsbn.setBounds(330, 390, 180, 30);
        getContentPane().add(FTTitulo);
        FTTitulo.setBounds(530, 130, 180, 30);
        getContentPane().add(FTAssunto);
        FTAssunto.setBounds(530, 390, 180, 30);
        getContentPane().add(FTNumEd);
        FTNumEd.setBounds(130, 220, 180, 30);
        getContentPane().add(FTPalChave1);
        FTPalChave1.setBounds(130, 460, 180, 30);
        getContentPane().add(FTCidade);
        FTCidade.setBounds(330, 220, 180, 30);
        getContentPane().add(FTEditora);
        FTEditora.setBounds(530, 220, 180, 30);
        getContentPane().add(FTChave2);
        FTChave2.setBounds(330, 460, 180, 30);
        getContentPane().add(FTAno);
        FTAno.setBounds(130, 310, 180, 30);

        FTTituloFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTTituloFimActionPerformed(evt);
            }
        });
        getContentPane().add(FTTituloFim);
        FTTituloFim.setBounds(330, 310, 180, 30);

        FTCdu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FTCduKeyPressed(evt);
            }
        });
        getContentPane().add(FTCdu);
        FTCdu.setBounds(530, 460, 180, 30);

        BInser.setText("INSERIR");
        BInser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInserActionPerformed(evt);
            }
        });
        getContentPane().add(BInser);
        BInser.setBounds(370, 510, 90, 22);

        BCancel.setText("CANCEL");
        getContentPane().add(BCancel);
        BCancel.setBounds(260, 510, 90, 22);

        CBAcervo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções>", "Livro", "Periodicos", "TCC", "Relatorios", "Midias", "Cartazes", "Mapas" }));
        CBAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAcervoActionPerformed(evt);
            }
        });
        getContentPane().add(CBAcervo);
        CBAcervo.setBounds(300, 60, 210, 22);

        BTelaIni.setText("Voltar Tela");
        BTelaIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTelaIniActionPerformed(evt);
            }
        });
        getContentPane().add(BTelaIni);
        BTelaIni.setBounds(480, 510, 90, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\samue\\Documents\\NetBeansProjects\\Bibliotecas\\src\\main\\java\\Imagens\\question-mark-5483259_960_720.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-60, -80, 1120, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FTTituloFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTTituloFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTTituloFimActionPerformed

    private void CBAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBAcervoActionPerformed

    }//GEN-LAST:event_CBAcervoActionPerformed

    private void BInserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInserActionPerformed
        
        
        Control crt = new Control();
        
        if(CBAcervo.getSelectedItem().equals("<Selecione uma das opções>")){
            
            
            JOptionPane.showMessageDialog(rootPane, "Acesso foi negado!\nEscolha Uma opcao valida");
        }
        else if(CBAcervo.getSelectedItem().equals("Livro")){
            
            try {
                crt.CadastroLivro(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Livro Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Periodicos")){
            
            try {
                crt.CadastroPeriodicos(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Periodicos Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("TCC")){
            
            try {
                crt.CadastroTCC(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "TCC Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Relatorios")){
            
            try {
                crt.CadastroRelatorios(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            
            JOptionPane.showMessageDialog(rootPane, "Relatorio Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Midias")){
            
            try {
                crt.CadastroMidias(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Midia Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Cartazes")){
            
            try {
                crt.CadastroCartazes(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Cartaze Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Mapas")){
            
            try {
                crt.CadastroMapas(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Mapa Adicionado");
        }
        
        limpa();
    }//GEN-LAST:event_BInserActionPerformed

    private void FTCduKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FTCduKeyPressed
        
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            Control crt = new Control();
        
        if(CBAcervo.getSelectedItem().equals("<Selecione uma das opções>")){
            
            
            JOptionPane.showMessageDialog(rootPane, "Acesso foi negado!\nEscolha Uma opcao valida");
        }
        else if(CBAcervo.getSelectedItem().equals("Livro")){
            
            try {
                crt.CadastroLivro(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Livro Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Periodicos")){
            
            try {
                crt.CadastroPeriodicos(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Periodicos Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("TCC")){
            
            try {
                crt.CadastroTCC(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "TCC Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Relatorios")){
            
            try {
                crt.CadastroRelatorios(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            
            JOptionPane.showMessageDialog(rootPane, "Relatorio Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Midias")){
            
            try {
                crt.CadastroMidias(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Midia Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Cartazes")){
            
            try {
                crt.CadastroCartazes(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Cartaze Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Mapas")){
            
            try {
                crt.CadastroMapas(FTAutor1.getText(),FTAutor2.getText(),FTTitulo.getText(),FTAno.getText(),FTAssunto.getText(),Integer.parseInt(FTCdu.getText()),FTChave2.getText(),FTCidade.getText(),FTEditora.getText(),Integer.parseInt(FTIsbn.getText()),Integer.parseInt(FTNumEd.getText()),Integer.parseInt(FTNumPag.getText()),FTPalChave1.getText(),Integer.parseInt(FTTam.getText()),FTTituloFim.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Mapa Adicionado");
        }
        
        limpa();
            }
    }//GEN-LAST:event_FTCduKeyPressed

    private void BTelaIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTelaIniActionPerformed
        TelaInicial Tl = new TelaInicial();
        setVisible(false);
        Tl.setVisible(true);      
    }//GEN-LAST:event_BTelaIniActionPerformed
    
    public void limpa(){
        
        FTAutor1.setText("");
        FTAutor2.setText("");
        FTTitulo.setText("");
        FTAno.setText("");
        FTAssunto.setText("");
        FTCdu.setText("");
        FTChave2.setText("");
        FTCidade.setText("");
        FTEditora.setText("");
        FTIsbn.setText("");
        FTNumEd.setText("");
        FTNumPag.setText("");
        FTPalChave1.setText("");
        FTTam.setText("");
        FTTituloFim.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInseriLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInseriLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInseriLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInseriLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInseriLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancel;
    private javax.swing.JButton BInser;
    private javax.swing.JButton BTelaIni;
    private javax.swing.JComboBox<String> CBAcervo;
    private javax.swing.JFormattedTextField FTAno;
    private javax.swing.JFormattedTextField FTAssunto;
    private javax.swing.JFormattedTextField FTAutor1;
    private javax.swing.JFormattedTextField FTAutor2;
    private javax.swing.JFormattedTextField FTCdu;
    private javax.swing.JFormattedTextField FTChave2;
    private javax.swing.JFormattedTextField FTCidade;
    private javax.swing.JFormattedTextField FTEditora;
    private javax.swing.JFormattedTextField FTIsbn;
    private javax.swing.JFormattedTextField FTNumEd;
    private javax.swing.JFormattedTextField FTNumPag;
    private javax.swing.JFormattedTextField FTPalChave1;
    private javax.swing.JFormattedTextField FTTam;
    private javax.swing.JFormattedTextField FTTitulo;
    private javax.swing.JFormattedTextField FTTituloFim;
    private javax.swing.JLabel LAno;
    private javax.swing.JLabel LAssunto;
    private javax.swing.JLabel LAutor1;
    private javax.swing.JLabel LAutor2;
    private javax.swing.JLabel LCdu;
    private javax.swing.JLabel LCidade;
    private javax.swing.JLabel LEdicao;
    private javax.swing.JLabel LEditora;
    private javax.swing.JLabel LIsbn;
    private javax.swing.JLabel LNumPag;
    private javax.swing.JLabel LPalChave1;
    private javax.swing.JLabel LPalChave2;
    private javax.swing.JLabel LTam;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JLabel LTituloFIm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
