package Interface;
/**
 *
 * @author samue
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTitulo = new javax.swing.JLabel();
        LFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MNLogin = new javax.swing.JMenu();
        MIAdmin = new javax.swing.JMenuItem();
        MNEmprestimo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 550));
        getContentPane().setLayout(null);

        LTitulo.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        LTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LTitulo.setText("BIBLIOTECA VIRTUAL");
        getContentPane().add(LTitulo);
        LTitulo.setBounds(190, 150, 450, 170);

        LFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\samue\\Documents\\NetBeansProjects\\Bibliotecas\\src\\main\\java\\Imagens\\biblioteca-vazia-com-estantes-de-livros_1308-72785.jpg")); // NOI18N
        getContentPane().add(LFundo);
        LFundo.setBounds(-440, -90, 1280, 610);

        MNLogin.setText("Login");
        MNLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNLoginActionPerformed(evt);
            }
        });

        MIAdmin.setText("Admin");
        MIAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIAdminActionPerformed(evt);
            }
        });
        MNLogin.add(MIAdmin);

        jMenuBar1.add(MNLogin);

        MNEmprestimo.setText("Emprestimo");
        MNEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNEmprestimoActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Empresta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MNEmprestimo.add(jMenuItem1);

        jMenuBar1.add(MNEmprestimo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MNLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNLoginActionPerformed
        
    }//GEN-LAST:event_MNLoginActionPerformed

    private void MIAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIAdminActionPerformed
        TelaLogin Tlogin = new TelaLogin();
        setVisible(false);
        Tlogin.setVisible(true);
    }//GEN-LAST:event_MIAdminActionPerformed

    private void MNEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNEmprestimoActionPerformed

    }//GEN-LAST:event_MNEmprestimoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaEmprestimo Te = new TelaEmprestimo();
        Te.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LFundo;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JMenuItem MIAdmin;
    private javax.swing.JMenu MNEmprestimo;
    private javax.swing.JMenu MNLogin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
