/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controler.Control;
import javax.swing.JOptionPane;

/**
 *
 * @author samue
 */
public class TelaEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form TelaEmprestimo
     */
    public TelaEmprestimo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FTCdu = new javax.swing.JFormattedTextField();
        LEmprestimo = new javax.swing.JLabel();
        LCdu = new javax.swing.JLabel();
        BPegar = new javax.swing.JButton();
        CBAcervo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(728, 501));
        getContentPane().setLayout(null);
        getContentPane().add(FTCdu);
        FTCdu.setBounds(190, 260, 317, 33);

        LEmprestimo.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        LEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        LEmprestimo.setText("Emprestimo");
        getContentPane().add(LEmprestimo);
        LEmprestimo.setBounds(190, 30, 420, 130);

        LCdu.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        LCdu.setForeground(new java.awt.Color(255, 255, 255));
        LCdu.setText("Digite o CDU do Livro");
        getContentPane().add(LCdu);
        LCdu.setBounds(190, 220, 240, 50);

        BPegar.setText("Pegar");
        BPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPegarActionPerformed(evt);
            }
        });
        getContentPane().add(BPegar);
        BPegar.setBounds(300, 380, 91, 36);

        CBAcervo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções>", "Livro", "Periodicos", "TCC", "Relatorios", "Midias", "Cartazes", "Mapas" }));
        getContentPane().add(CBAcervo);
        CBAcervo.setBounds(250, 170, 189, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\samue\\Documents\\NetBeansProjects\\JavaApplication1\\src\\Imagens\\Doao-de-Livros.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPegarActionPerformed
        Control crt = new Control();
        
        if(CBAcervo.getSelectedItem().equals("<Selecione uma das opções>")){
            
            
            JOptionPane.showMessageDialog(rootPane, "Acesso foi negado!\nEscolha Uma opcao valida");
        }
        else if(CBAcervo.getSelectedItem().equals("Livro")){
            
            try {
                crt.pegaLivro(Integer.parseInt(FTCdu.getText()));
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Livro Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Periodicos")){
            
            try {
                crt.pegaPeriodicos(Integer.parseInt(FTCdu.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Periodicos Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("TCC")){
            
            try {
                crt.pegaTcc(Integer.parseInt(FTCdu.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "TCC Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Relatorios")){
            
            try {
                crt.pegaRelatorios(Integer.parseInt(FTCdu.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            
            JOptionPane.showMessageDialog(rootPane, "Relatorio Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Midias")){
            
            try {
                crt.pegaMidias(Integer.parseInt(FTCdu.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Midia Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Cartazes")){
            
            try {
                crt.pegaCartazes(Integer.parseInt(FTCdu.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Cartaze Adicionado");
        }
        
        else if(CBAcervo.getSelectedItem().equals("Mapas")){
            
            try {
                crt.pegaMapas(Integer.parseInt(FTCdu.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro!");
            }
            JOptionPane.showMessageDialog(rootPane, "Mapa Adicionado");
        }
        
        //limpa();
    }//GEN-LAST:event_BPegarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPegar;
    private javax.swing.JComboBox<String> CBAcervo;
    private javax.swing.JFormattedTextField FTCdu;
    private javax.swing.JLabel LCdu;
    private javax.swing.JLabel LEmprestimo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
