/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author samue
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LImagemFundo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LSenha = new javax.swing.JLabel();
        TFLogin = new javax.swing.JFormattedTextField();
        LLogin = new javax.swing.JLabel();
        LTitulo = new javax.swing.JLabel();
        ButtonCancel = new javax.swing.JButton();
        ButtonLogin = new javax.swing.JButton();
        PFSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        LImagemFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\samue\\Documents\\NetBeansProjects\\Bibliotecas\\src\\main\\java\\Imagens\\sala-vazia-com-estantes-de-madeira_33099-1727.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(null);

        LSenha.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        LSenha.setForeground(new java.awt.Color(255, 255, 255));
        LSenha.setText("PASSWORD:");
        jPanel1.add(LSenha);
        LSenha.setBounds(290, 350, 140, 20);
        jPanel1.add(TFLogin);
        TFLogin.setBounds(290, 280, 230, 30);

        LLogin.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        LLogin.setForeground(new java.awt.Color(255, 255, 255));
        LLogin.setText("LOGIN:");
        jPanel1.add(LLogin);
        LLogin.setBounds(290, 220, 110, 50);

        LTitulo.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        LTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LTitulo.setText("BEM VINDO A BIBLIOTECA");
        jPanel1.add(LTitulo);
        LTitulo.setBounds(150, 30, 540, 130);

        ButtonCancel.setText("CADASTRAR");
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCancel);
        ButtonCancel.setBounds(350, 490, 110, 30);

        ButtonLogin.setText("LOGIN");
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });
        ButtonLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonLoginKeyPressed(evt);
            }
        });
        jPanel1.add(ButtonLogin);
        ButtonLogin.setBounds(350, 450, 110, 30);

        PFSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PFSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(PFSenha);
        PFSenha.setBounds(290, 390, 230, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\samue\\Documents\\NetBeansProjects\\Bibliotecas\\src\\main\\java\\Imagens\\sala-vazia-com-estantes-de-madeira_33099-1727.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-460, -110, 1370, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        
        if(TFLogin.getText().equals("admin")&&PFSenha.getText().equals("7279")){
            
            TelaInseriLivro Tinser = new TelaInseriLivro();
                Tinser.setVisible(true);
            
                dispose();
        }
        
        else{
            JOptionPane.showMessageDialog(rootPane, "Acesso foi negado!");
        }
    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        
        
        Cadastro cad = new Cadastro();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void ButtonLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonLoginKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            if(TFLogin.getText().equals("admin")&&PFSenha.getText().equals("7279")){
            
            TelaInseriLivro Tinser = new TelaInseriLivro();
                Tinser.setVisible(true);
            
                dispose();
            }
        
            else{
                JOptionPane.showMessageDialog(rootPane, "Acesso foi negado!");
            }  
        }
    }//GEN-LAST:event_ButtonLoginKeyPressed

    private void PFSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PFSenhaKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            if(TFLogin.getText().equals("admin")&&PFSenha.getText().equals("7279")){
            
            TelaInseriLivro Tinser = new TelaInseriLivro();
                Tinser.setVisible(true);
            
                dispose();
            }
        
            else{
                JOptionPane.showMessageDialog(rootPane, "Acesso foi negado!");
            }  
        }
    }//GEN-LAST:event_PFSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JLabel LImagemFundo;
    private javax.swing.JLabel LLogin;
    private javax.swing.JLabel LSenha;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JPasswordField PFSenha;
    private javax.swing.JFormattedTextField TFLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
